package com.ironhack.TheDataLayerHomework3.enums;

public enum NavigationEnum {

    //lead
    NEW_LEAD, SHOW_LEADS, LOOKUP_LEAD, CONVERT_LEAD,

    //opportunity
    CHANGE_STATUS,

    //sales rep
    NEW_SALESREP, SHOW_SALESREPS,

    EXIT,

    //by sales rep
    REPORT_LEAD_SALESREP, REPORT_OPPORTUNITY_SALESREP, REPORT_CLOSED_WON_SALESREP, REPORT_CLOSED_LOST_SALESREP, REPORT_OPEN_SALESREP,

    //by product
    REPORT_OPPORTUNITY_PRODUCT, REPORT_CLOSED_WON_PRODUCT, REPORT_CLOSED_LOST_PRODUCT, REPORT_OPEN_PRODUCT,

    //by country
    REPORT_OPPORTUNITY_COUNTRY, REPORT_CLOSED_WON_COUNTRY, REPORT_CLOSED_LOST_COUNTRY, REPORT_OPEN_COUNTRY,

    //by city
    REPORT_OPPORTUNITY_CITY, REPORT_CLOSED_WON_CITY, REPORT_CLOSED_LOST_CITY, REPORT_OPEN_CITY,

    //by industry
    REPORT_OPPORTUNITY_INDUSTRY, REPORT_CLOSED_WON_INDUSTRY, REPORT_CLOSED_LOST_INDUSTRY, REPORT_OPEN_INDUSTRY,

    //employee count states
    MEAN_EMPLOYEE_COUNT, MEDIAN_EMPLOYEE_COUNT, MAX_EMPLOYEE_COUNT, MIN_EMPLOYEE_COUNT,

    //quantity states
    MEAN_QUANTITY, MEDIAN_QUANTITY, MAX_QUANTITY, MIN_QUANTITY,

    //opportunity states
    MEAN_OPPS_ACCOUNT, MEDIAN_OPPS_ACCOUNT, MAX_OPPS_ACCOUNT, MIN_OPPS_ACCOUNT,
}
